/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const AttachmentType: core.serialization.Schema<
    serializers.forms.AttachmentType.Raw,
    Typeform.forms.AttachmentType
> = core.serialization.enum_(["image", "video"]);

export declare namespace AttachmentType {
    type Raw = "image" | "video";
}
