/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormImage: core.serialization.ObjectSchema<serializers.FormImage.Raw, Typeform.FormImage> =
    core.serialization.object({
        href: core.serialization.string().optional(),
    });

export declare namespace FormImage {
    interface Raw {
        href?: string | null;
    }
}
