/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormMeta: core.serialization.ObjectSchema<serializers.FormMeta.Raw, Typeform.FormMeta> =
    core.serialization.object({
        allowIndexing: core.serialization.property("allow_indexing", core.serialization.boolean().optional()),
        description: core.serialization.string().optional(),
        image: core.serialization.lazyObject(async () => (await import("../../..")).FormImage).optional(),
    });

export declare namespace FormMeta {
    interface Raw {
        allow_indexing?: boolean | null;
        description?: string | null;
        image?: serializers.FormImage.Raw | null;
    }
}
