/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormField: core.serialization.ObjectSchema<serializers.forms.FormField.Raw, Typeform.forms.FormField> =
    core.serialization.object({
        ref: core.serialization.string().optional(),
        title: core.serialization.string(),
    });

export declare namespace FormField {
    interface Raw {
        ref?: string | null;
        title: string;
    }
}
