/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormMetadata: core.serialization.ObjectSchema<
    serializers.forms.FormMetadata.Raw,
    Typeform.forms.FormMetadata
> = core.serialization.object({
    allowIndexing: core.serialization.property("allow_indexing", core.serialization.boolean().optional()),
    description: core.serialization.string().optional(),
    image: core.serialization.lazyObject(async () => (await import("../../..")).forms.ImageUrl).optional(),
});

export declare namespace FormMetadata {
    interface Raw {
        allow_indexing?: boolean | null;
        description?: string | null;
        image?: serializers.forms.ImageUrl.Raw | null;
    }
}
