/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormVariables: core.serialization.ObjectSchema<
    serializers.forms.FormVariables.Raw,
    Typeform.forms.FormVariables
> = core.serialization.object({
    score: core.serialization.number().optional(),
    price: core.serialization.number().optional(),
});

export declare namespace FormVariables {
    interface Raw {
        score?: number | null;
        price?: number | null;
    }
}
