/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const FormNotificationSettings: core.serialization.ObjectSchema<
    serializers.forms.FormNotificationSettings.Raw,
    Typeform.forms.FormNotificationSettings
> = core.serialization.object({
    self: core.serialization.lazyObject(async () => (await import("../../..")).forms.NotificationSettings).optional(),
    respondent: core.serialization
        .lazyObject(async () => (await import("../../..")).forms.NotificationSettings)
        .optional(),
});

export declare namespace FormNotificationSettings {
    interface Raw {
        self?: serializers.forms.NotificationSettings.Raw | null;
        respondent?: serializers.forms.NotificationSettings.Raw | null;
    }
}
