/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const NotificationSettings: core.serialization.ObjectSchema<
    serializers.forms.NotificationSettings.Raw,
    Typeform.forms.NotificationSettings
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
    recipient: core.serialization.string(),
    replyTo: core.serialization.property("reply_to", core.serialization.list(core.serialization.string()).optional()),
    subject: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace NotificationSettings {
    interface Raw {
        enabled?: boolean | null;
        recipient: string;
        reply_to?: string[] | null;
        subject: string;
        message: string;
    }
}
