/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const Notifications: core.serialization.ObjectSchema<serializers.Notifications.Raw, Typeform.Notifications> =
    core.serialization.object({
        self: core.serialization.lazyObject(async () => (await import("../../..")).NotificationsSelf).optional(),
    });

export declare namespace Notifications {
    interface Raw {
        self?: serializers.NotificationsSelf.Raw | null;
    }
}
