/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const NotificationsSelf: core.serialization.ObjectSchema<
    serializers.NotificationsSelf.Raw,
    Typeform.NotificationsSelf
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
    recipients: core.serialization.list(core.serialization.string()),
    replyTo: core.serialization.property("reply_to", core.serialization.string().optional()),
    subject: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace NotificationsSelf {
    interface Raw {
        enabled?: boolean | null;
        recipients: string[];
        reply_to?: string | null;
        subject: string;
        message: string;
    }
}
