/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const ProgressBarType: core.serialization.Schema<
    serializers.forms.ProgressBarType.Raw,
    Typeform.forms.ProgressBarType
> = core.serialization.enum_(["percentage", "proportion"]);

export declare namespace ProgressBarType {
    type Raw = "percentage" | "proportion";
}
