/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const WorkspaceUrl: core.serialization.ObjectSchema<
    serializers.forms.WorkspaceUrl.Raw,
    Typeform.forms.WorkspaceUrl
> = core.serialization.object({
    href: core.serialization.string().optional(),
});

export declare namespace WorkspaceUrl {
    interface Raw {
        href?: string | null;
    }
}
