/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateOrUpdateWebhookRequest {
    url?: string;
    enabled?: boolean;
    secret?: string;
    verifySsl?: boolean;
}
