/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../../core";

export const CreateFormRequest: core.serialization.Schema<
    serializers.CreateFormRequest.Raw,
    Typeform.CreateFormRequest
> = core.serialization.object({
    title: core.serialization.string().optional(),
});

export declare namespace CreateFormRequest {
    interface Raw {
        title?: string | null;
    }
}
