/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Typeform } from "@fern-api/typeform";

export interface CreateThemeRequest {
    background?: Typeform.BackgroundSettings;
    colors: Typeform.ThemeColors;
    font: Typeform.Font;
    hasTransparentButton?: boolean;
    name: string;
}
