/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../../core";

export const CreateOrUpdateWebhookRequest: core.serialization.Schema<
    serializers.CreateOrUpdateWebhookRequest.Raw,
    Typeform.CreateOrUpdateWebhookRequest
> = core.serialization.object({
    url: core.serialization.string().optional(),
    enabled: core.serialization.boolean().optional(),
    secret: core.serialization.string().optional(),
    verifySsl: core.serialization.property("verify_ssl", core.serialization.boolean().optional()),
});

export declare namespace CreateOrUpdateWebhookRequest {
    interface Raw {
        url?: string | null;
        enabled?: boolean | null;
        secret?: string | null;
        verify_ssl?: boolean | null;
    }
}
