/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Typeform } from "@fern-api/typeform";

/**
 * Settings for the background.
 */
export interface BackgroundSettings {
    /** Background image URL. */
    href?: string;
    /** Layout for the background. */
    layout?: Typeform.BackgroundLayout;
    /** Brightness for the background. `-1` is least bright (minimum) and `1` is most bright (maximum). */
    brightness?: number;
}
