/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Layout for the background.
 */
export type BackgroundLayout = "fullscreen" | "repeat" | "no-repeat";

export const BackgroundLayout = {
    Fullscreen: "fullscreen",
    Repeat: "repeat",
    NoRepeat: "no-repeat",
} as const;
