/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Font for the theme.
 */
export type Font =
    | "Acme"
    | "Arial"
    | "Arvo"
    | "Bangers"
    | "Cabin"
    | "Courier"
    | "Exo"
    | "Georgia"
    | "Handlee"
    | "Karla"
    | "Lato"
    | "Lekton"
    | "Lobster"
    | "Lora"
    | "McLaren"
    | "Montserrat"
    | "Oswald"
    | "Quicksand"
    | "Raleway"
    | "Signika"
    | "Sniglet"
    | "Vollkorn";

export const Font = {
    Acme: "Acme",
    Arial: "Arial",
    Arvo: "Arvo",
    Bangers: "Bangers",
    Cabin: "Cabin",
    Courier: "Courier",
    Exo: "Exo",
    Georgia: "Georgia",
    Handlee: "Handlee",
    Karla: "Karla",
    Lato: "Lato",
    Lekton: "Lekton",
    Lobster: "Lobster",
    Lora: "Lora",
    McLaren: "McLaren",
    Montserrat: "Montserrat",
    Oswald: "Oswald",
    Quicksand: "Quicksand",
    Raleway: "Raleway",
    Signika: "Signika",
    Sniglet: "Sniglet",
    Vollkorn: "Vollkorn",
} as const;
