/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Colors the theme will apply to answers, background, buttons, and questions.
 */
export interface ThemeColors {
    /** Color the theme will apply to answers. Hexadecimal value. */
    answer: string;
    /** Color the theme will apply to the background. Hexadecimal value. */
    background: string;
    /** Color the theme will apply to buttons. Hexadecimal value. */
    button: string;
    /** Color the theme will apply to questions. Hexadecimal value. */
    question: string;
}
