/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const BackgroundLayout: core.serialization.Schema<serializers.BackgroundLayout.Raw, Typeform.BackgroundLayout> =
    core.serialization.enum_(["fullscreen", "repeat", "no-repeat"]);

export declare namespace BackgroundLayout {
    type Raw = "fullscreen" | "repeat" | "no-repeat";
}
