/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Typeform } from "@fern-api/typeform";
import * as core from "../../../../core";

export const BackgroundSettings: core.serialization.ObjectSchema<
    serializers.BackgroundSettings.Raw,
    Typeform.BackgroundSettings
> = core.serialization.object({
    href: core.serialization.string().optional(),
    layout: core.serialization.lazy(async () => (await import("../../..")).BackgroundLayout).optional(),
    brightness: core.serialization.number().optional(),
});

export declare namespace BackgroundSettings {
    interface Raw {
        href?: string | null;
        layout?: serializers.BackgroundLayout.Raw | null;
        brightness?: number | null;
    }
}
