/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of attachment.
 */
export type AttachmentType = "image" | "video";

export const AttachmentType = {
    Image: "image",
    Video: "video",
} as const;
