/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Reference for properties in a field. The required fields and properties depend on the `type` value.
 */
export interface FormField {
    /** Readable name you can use to reference the field. */
    ref?: string;
    /** Unique name you assign to the field on this form. */
    title: string;
}
