/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FormVariables {
    /** Recall Information for keeping score as users answer each question (for example, for quizzes). */
    score?: number;
    /** Recall Information for tracking the total price of all items users select (for example, for shopping carts, donation campaigns, and payment collections). */
    price?: number;
}
