/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Typeform } from "@fern-api/typeform";

export interface FormMetadata {
    /** true to allow search engines to index your typeform. Otherwise, false. */
    allowIndexing?: boolean;
    /** Description for search engines to display for your typeform. */
    description?: string;
    image?: Typeform.forms.ImageUrl;
}
