/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Typeform } from "@fern-api/typeform";

export interface FormNotificationSettings {
    /** Settings for notifications sent when respondents complete and submit the typeform. */
    self?: Typeform.forms.NotificationSettings;
    /** Settings for notifications sent to respondents immediately after submitting the typeform. */
    respondent?: Typeform.forms.NotificationSettings;
}
