/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Language =
    | "en"
    | "es"
    | "ca"
    | "fr"
    | "de"
    | "ru"
    | "it"
    | "da"
    | "pt"
    | "ch"
    | "zh"
    | "nl"
    | "no"
    | "uk"
    | "ja"
    | "ko"
    | "hr"
    | "fi"
    | "sv"
    | "pl"
    | "el"
    | "hu"
    | "tr"
    | "cs"
    | "et"
    | "di";

export const Language = {
    En: "en",
    Es: "es",
    Ca: "ca",
    Fr: "fr",
    De: "de",
    Ru: "ru",
    It: "it",
    Da: "da",
    Pt: "pt",
    Ch: "ch",
    Zh: "zh",
    Nl: "nl",
    No: "no",
    Uk: "uk",
    Ja: "ja",
    Ko: "ko",
    Hr: "hr",
    Fi: "fi",
    Sv: "sv",
    Pl: "pl",
    El: "el",
    Hu: "hu",
    Tr: "tr",
    Cs: "cs",
    Et: "et",
    Di: "di",
} as const;
