/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Settings for notifications sent when respondents complete and submit the typeform.
 */
export interface NotificationsSelf {
    /** true to send notifications. false to disable notifications. */
    enabled?: boolean;
    recipients: string[];
    /** Email address to use for notification Reply-To. Must be a Recall Information value based on respondent's answer to a field: {{field:ref}} or {{hidden:ref}}. */
    replyTo?: string;
    /** Subject to use for the notification email. Can combine text and Recall Information value from one or more fields. Available Recall Information values are {{form:title}}, {{account:email}}, {{account:name}}, {{link:report}}, and standard Recall Information for fields {{field:ref}} and hidden fields {{hidden:ref}}. */
    subject: string;
    /** Message to include in the body of the notification email. Can combine text and Recall Information value from one or more fields. Available Recall Information values are {{form:title}}, {{account:email}}, {{account:name}}, {{link:report}}, {{form:all_answers}}, and standard Recall Information for fields {{field:ref}} and hidden fields {{hidden:ref}}. You can format messages with bold (`*bold*`) and italic (`_italic_`) text. HTML tags are forbidden. */
    message: string;
}
