/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Basis for the progress bar displayed on the screen. Choose "proportion" to show the number of questions answered so far. Choose "percentage" to show the percentage of questions answered so far.
 */
export type ProgressBarType = "percentage" | "proportion";

export const ProgressBarType = {
    Percentage: "percentage",
    Proportion: "proportion",
} as const;
