/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ThankYouScreen {
    /** Readable name you can use to reference the thank you screen. */
    ref?: string;
    /** Title for the thank you screen. */
    title: string;
}
