/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WelcomeScreen {
    /** Readable name you can use to reference the welcome screen. */
    ref?: string;
    /** Title for the welcome screen. */
    title: string;
}
