/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * URL of the workspace to use for the typeform. If you don't specify a URL for the workspace, Typeform saves the form in the default workspace.
 */
export interface WorkspaceUrl {
    href?: string;
}
