/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteReponseRequest {
    /**
     * Comma-separated list of tokens of the responses to delete. You can list up to **1000** tokens.
     */
    includedTokens: string;
}
