/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListReponsesRequest {
    /**
     * Maximum number of responses. Default value is **25**. Maximum value is **1000**. If your typeform has fewer than 1000 responses, you can retrieve all of the responses in a single request by adding the `page_size` parameter. If your typeform has more than 1000 responses, use the [`since` and `until`](responses/walkthroughs#use-the-since-and-until-query-parameters-to-retrieve-a-date-range) or [`after`](responses/walkthroughs#use-the-after-query-parameter-to-paginate) query parameters to narrow the scope of your request.
     */
    pageSize?: number;
    /**
     * Limit request to responses submitted since the specified date and time. In ISO 8601 format, UTC time, to the second, with T as a delimiter between the date and time. See the [Responses Walkthroughs](/responses/walkthroughs/#use-query-parameters-to-retrieve-specific-data) for an example request that uses the `since` parameter.
     */
    since?: string;
    /**
     * Limit request to responses submitted until the specified date and time. In ISO 8601 format, UTC time, to the second, with T as a delimiter between the date and time. See the [Responses Walkthroughs](/responses/walkthroughs/#use-query-parameters-to-retrieve-specific-data) for an example request that uses the `until` parameter.
     */
    until?: string;
    /**
     * Limit request to responses submitted after the specified token. If you use the `after` parameter, the responses will be sorted in the order that our system processed them (instead of the default order, `submitted_at`). This ensures that you can traverse the complete set of responses without repeating entries. See the [Responses Walkthroughs](/responses/walkthroughs/#use-query-parameters-to-retrieve-specific-data) for an example request that uses the `after` parameter.
     */
    after?: string;
    /**
     * Limit request to responses submitted before the specified token. If you use the `before` parameter, the responses will be sorted in the order that our system processed them (instead of the default order, `submitted_at`). This ensures that you can traverse the complete set of responses without repeating entries.
     */
    before?: string;
    /**
     * Limit request to the specified `response_id` values. Use a comma-separated list to specify more than one `response_id` value.
     */
    includedResponseIds?: string;
    /**
     * true if form was submitted. Otherwise, false.
     */
    completed?: boolean;
    /**
     * Order of responses. Currently, responses are automatically sorted by `submitted_at,desc`---the date they were submitted, from newest to oldest. We plan to add more options for sort order soon.
     */
    sort?: string;
    /**
     * Limit request to only responses that that include the specified string. You can specify any string as the `query` value. The string will be escaped, and the query will include Hidden Fields.
     */
    query?: string;
}
