/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ResponsesClient } from "./api/resources/responses/client/Client";
import { Client as AccountsClient } from "./api/resources/accounts/client/Client";
import { Client as FormsClient } from "./api/resources/forms/client/Client";

export declare namespace TypeformClient {
    interface Options {
        environment: environments.TypeformEnvironment | string;
        apiKey?: core.Supplier<string>;
    }
}

export class TypeformClient {
    constructor(private readonly options: TypeformClient.Options) {}

    #responses: ResponsesClient | undefined;

    public get responses(): ResponsesClient {
        return (this.#responses ??= new ResponsesClient(this.options));
    }

    #accounts: AccountsClient | undefined;

    public get accounts(): AccountsClient {
        return (this.#accounts ??= new AccountsClient(this.options));
    }

    #forms: FormsClient | undefined;

    public get forms(): FormsClient {
        return (this.#forms ??= new FormsClient(this.options));
    }
}
