/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const TypeformEnvironment = {
    Production: "https://api.typeform.com/",
} as const;

export type TypeformEnvironment = typeof TypeformEnvironment.Production;
