/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Typeform } from "@fern-api/typeform";

export interface CreateThemeRequest {
    title: string;
    settings?: Typeform.forms.FormSettings;
    theme?: string;
    workspace: Typeform.forms.WorkspaceUrl;
    hidden?: string[];
    variables?: Typeform.forms.FormVariables;
    welcomeScreens?: Typeform.forms.WelcomeScreen[];
    thankyouScreens?: Typeform.forms.ThankYouScreen[];
    fields?: Typeform.forms.FormField[];
}
